"""empty message

Revision ID: 7b34fa355ab8
Revises: 
Create Date: 2022-07-31 10:57:36.631160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b34fa355ab8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('state_id', table_name='lga')
    op.drop_table('lga')
    op.alter_column('admin', 'stateid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('admin_ibfk_5', 'admin', type_='foreignkey')
    op.drop_constraint('admin_ibfk_6', 'admin', type_='foreignkey')
    op.drop_constraint('admin_ibfk_1', 'admin', type_='foreignkey')
    op.drop_constraint('admin_ibfk_2', 'admin', type_='foreignkey')
    op.drop_constraint('admin_ibfk_4', 'admin', type_='foreignkey')
    op.drop_constraint('admin_ibfk_3', 'admin', type_='foreignkey')
    op.create_foreign_key(None, 'admin', 'categories', ['categoryid'], ['categoryid'])
    op.create_foreign_key(None, 'admin', 'payments', ['paymentid'], ['paymentid'])
    op.create_foreign_key(None, 'admin', 'user', ['userid'], ['userid'])
    op.create_foreign_key(None, 'admin', 'products', ['productid'], ['productid'])
    op.create_foreign_key(None, 'admin', 'state', ['stateid'], ['stateid'])
    op.create_foreign_key(None, 'admin', 'orders', ['orderid'], ['orderid'])
    op.create_foreign_key(None, 'admin', 'vendor', ['vendorid'], ['vendorid'])
    op.alter_column('categories', 'category_img',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.create_foreign_key(None, 'order_details', 'orders', ['orderid'], ['orderid'])
    op.create_foreign_key(None, 'order_details', 'products', ['productid'], ['productid'])
    op.create_foreign_key(None, 'orders', 'user', ['userid'], ['userid'])
    op.alter_column('payments', 'paymentref',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('payments_ibfk_2', 'payments', type_='foreignkey')
    op.drop_constraint('payments_ibfk_1', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['orderid'], ['orderid'])
    op.create_foreign_key(None, 'payments', 'user', ['userid'], ['userid'])
    op.alter_column('vendor', 'vendor_img',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor', 'vendor_img',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_ibfk_1', 'payments', 'user', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('payments_ibfk_2', 'payments', 'orders', ['orderid'], ['orderid'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('payments', 'paymentref',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.drop_constraint(None, 'order_details', type_='foreignkey')
    op.alter_column('categories', 'category_img',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.drop_constraint(None, 'admin', type_='foreignkey')
    op.create_foreign_key('admin_ibfk_3', 'admin', 'vendor', ['vendorid'], ['vendorid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('admin_ibfk_4', 'admin', 'orders', ['orderid'], ['orderid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('admin_ibfk_2', 'admin', 'categories', ['categoryid'], ['categoryid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('admin_ibfk_1', 'admin', 'user', ['userid'], ['userid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('admin_ibfk_6', 'admin', 'payments', ['paymentid'], ['paymentid'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key('admin_ibfk_5', 'admin', 'products', ['productid'], ['productid'], onupdate='CASCADE', ondelete='CASCADE')
    op.alter_column('admin', 'stateid',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_table('lga',
    sa.Column('lga_id', mysql.INTEGER(display_width=10, unsigned=True), autoincrement=True, nullable=False),
    sa.Column('stateid', mysql.INTEGER(display_width=11), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('lga_name', mysql.VARCHAR(length=50), server_default=sa.text("''"), nullable=False),
    sa.PrimaryKeyConstraint('lga_id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    op.create_index('state_id', 'lga', ['stateid'], unique=False)
    # ### end Alembic commands ###
